### ISSUE TITLE
Sy-toan To do carry over

### ISSUE THREAD

**Issue by annaspiers** [RS-PRISMATIC/PRISMATIC#22]
# Todo
 - [x] Data acquisition and data processing of inventory data
 - [x] Data acquisition and data processing of NEON plots
 - [x] Data acquisition and data processing of LiDAR data
 - [x] Encode allometric equations
 - [x] Calculate individual/plot-level biomass given stem diameter/basal stem diameter
 - [x] Seperate plots into 400m2 subplots
 - [x] Setup GitHub actions
 - [ ] Add unit tests and integration tests
 - [x] Add diagnostics
 - [x] Add logging
 - [x] Refactor configuration files
 - [x] Calculate Leaf Area Density
 - [x] Segment LAD into levels
